# Generated by Django 5.2.1 on 2026-01-23 05:51

import apps.charity.utils
import django.db.models.deletion
import django.utils.timezone
import django_editorjs_fields.fields
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=apps.charity.utils.UploadToPathAndRename('image'), variations={'icon': (70, 70, True), 'large': (600, 400, True), 'thumbnail': (300, 200, True)})),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('event_start_time', models.TimeField(default=django.utils.timezone.now)),
                ('event_end_time', models.TimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charity.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
