# Generated by Django 5.2.1 on 2025-05-30 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_city_alter_event_country_delete_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
    ]
