# Generated by Django 5.2.1 on 2026-01-23 05:51

import apps.charity.utils
import django.utils.timezone
import django_editorjs_fields.fields
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=apps.charity.utils.UploadToPathAndRename('image'), variations={'icon': (80, 80, True), 'large': (600, 400, True), 'thumbnail': (380, 250, True)})),
                ('raised', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
