# Generated by Django 5.2.1 on 2025-05-29 20:53

import apps.base.utils
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=apps.base.utils.UploadToPathAndRename('image'), variations={'icon': (80, 80, True), 'large': (600, 400, True), 'thumbnail': (380, 250, True)}),
        ),
    ]
