# Generated by Django 5.2.1 on 2026-01-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
