# Generated by Django 5.2.1 on 2026-01-29 07:47

import apps.charity.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.charity.utils.UploadToPathAndRename('icons')),
        ),
    ]
