# Generated by Django 5.2.1 on 2025-06-01 08:13

import apps.base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.base.utils.UploadToPathAndRename('images')),
        ),
    ]
