# Generated by Django 5.2.1 on 2026-01-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_testimonial_priority_alter_testimonial_avatar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
