# Generated by Django 5.2.1 on 2025-05-30 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_social_site_remove_social_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.role'),
            preserve_default=False,
        ),
    ]
