# Generated by Django 5.2.1 on 2025-05-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
