# Generated by Django 5.2.1 on 2025-05-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_member_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
