# Generated by Django 5.2.1 on 2025-05-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_social_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='logo',
            new_name='fontawesome_class',
        ),
    ]
