# Generated by Django 5.2.1 on 2025-06-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_logo_social_fontawesome_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
    ]
