# Generated by Django 5.2.1 on 2025-05-28 06:37

import apps.base.utils
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=apps.base.utils.UploadToPathAndRename('images'), variations={'icon': (90, 90, True), 'profile': (200, 200, True)}),
        ),
    ]
