# Generated by Django 5.2.1 on 2025-06-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
