# Generated by Django 5.2.1 on 2025-06-01 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_logo_social_fontawesome_class'),
        ('users', '0004_user_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.role'),
        ),
    ]
