# Generated by Django 5.2.1 on 2025-05-28 06:09

import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
            ],
        ),
    ]
